### ISSUE TITLE
Enhancement to add the Map<V, List<?> support.

### ISSUE THREAD

**Issue by abdallah-rashwan** [smallrye/smallrye-config#1008]
It is not supported to map properties as key and list of values to a Map<V, List<?>, the only way is to use custom interfaces which is not the best solution. so I would recommend to add this feature to handle it easier and to save a lot of development time.
Here's an issue on stackoverflow [https://stackoverflow.com/questions/70025830/injecting-a-map-of-lists-into-configuration](url) showing an example.

**Comment by radcortez** [comment]
We already support `Map<V, List<?>`.

Although the `yaml` in SO:

```yaml
app:
  example:
  - key: KeyExample
    values:
    - test 1
    - test 2
    - test 3
  - key: KeyExample2
    values:
    - test 1
    - test 2
    - test 3
```

Requires the following mapping:

```
@ConfigMapping(prefix = "app")
interface MapLists {
    List<Example> example();

    interface Example {
        String key();

        List<String> values();
    }
}
```

This is because a key in a `Map` has to be part of the path, and in this case is just an arbitrary proprietary, so we have no way to know which property should be the key.

To map that with `Map<V, List<?>`, the `yaml` should look like:

```yaml
app:
  example:
    KeyExample:
     - test 1
     - test 2
     - test 3
    KeyExample2:
     - test 1
     - test 2
     - test 3
```

And the mapping:

```java
@ConfigMapping(prefix = "app.example")
interface MapLists {
    @WithParentName
    Map<String, List<String>> example();
}
```
