### ISSUE TITLE
3.10+ - Yaml lists are out of order

### ISSUE THREAD

**Issue by mikethecalamity** [smallrye/smallrye-config#1305]
When upgrading Quarkus, I noticed that lists defined the YAML way in the `application.yaml` are read in a different order than defined in the config. This issue only began in `3.10.0` (and still exists in `3.11.2`). It seems to only be an issue when the list has 11 or more items. And is not an issue with comma-defined lists.

### Confg
```yaml
yaml-list:
  - thingA
  - thingB
  - thingC
  - thingD
  - thingE
  - thingF
  - thingG
  - thingH
  - thingI
  - thingJ
  - thingK
comma-list: thingA,thingB,thingC,thingD,thingE,thingF,thingG,thingH,thingI,thingJ,thingK
```

### Result
```
yaml-list  = [thingA, thingK, thingB, thingC, thingD, thingE, thingF, thingG, thingH, thingI, thingJ]
comma-list = [thingA, thingB, thingC, thingD, thingE, thingF, thingG, thingH, thingI, thingJ, thingK]
```

### Reproducer
1. Clone `https://github.com/mikethecalamity/quarkus-test`
2. Run `gradlew -p apps service3:test`
3. Note the test using the comma-separated list succeeds and the test using the yaml list fails
