### ISSUE TITLE
SmallRye Config to cater for multi nested List of properties

### ISSUE THREAD

**Issue by ismailsalloo** [smallrye/smallrye-config#436]
Description
SmallRye Config to cater for multi nested List of properties

Implementation Idea
Example of how the application.properties/application.yaml file can be set up with nested properties:
eg application.properties:
```
application.environments[0].name=dev
application.environments[0].service[0].name=service1
application.environments[0].service[1].name=service2
application.environments[0].service[2].name=service3
```
eg application.yaml:
```
application:
  environments:
    - name: dev
      services:
        - name: service1
        - name: service2
        - name: service3
```
We then can have a Java ConfigMapping Class as follows:

```
@ConfigMapping(prefix = "application.environments")
public interface AppConfiguration {
  @WithParentName
  List<Environment> environments();

  interface Environment {
    
    @WithParentName
    String name();

    @WithParentName
    List<Service> services();

    interface Service {

      @WithParentName
      String name();
    }
  }
}
```
