### ISSUE TITLE
feature: Support intermediate config directories in FileSystemConfigSource like /configs.d/*/

### ISSUE THREAD

**Issue by vladimirfx** [smallrye/smallrye-config#693]
In process of migrating some Spring Boot projects to Quarkus, we discover a lack of this feature.
Our current Pod config looks like this:

```yaml
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: optional:configtree:/config.d/*/
```

At deployment time Ops team projects secrets like that:
```yaml
          volumeMounts:
            - name: activemq-config
              mountPath: /config/activemq
              readOnly: true
            - name: smtp-config
              mountPath: /config.d/smpt
              readOnly: true
            - name: database-config
              mountPath: /config.d/database
              readOnly: true
```

In different environments, the exact number and target of such volume mounts may differ (ex. SMTP config set by main app config in DEV).

It would be nice if this work in Quarkus:
```yaml
          env:
            - name: SMALLRYE_CONFIG_SOURCE_FILE_LOCATIONS
              value: /config.d/*/
```

if you are OK with that feature I can provide a PR.
