### ISSUE TITLE
Nested of Optionals and Maps is broken when YAMLSource is used 

### ISSUE THREAD

**Issue by gastaldi** [smallrye/smallrye-config#762]
_Original issue: https://github.com/quarkusio/quarkus/issues/26009_

Having a `ConfigMapping` like:

```java
@ConfigMapping(prefix = "message-util-configurations", namingStrategy = ConfigMapping.NamingStrategy.KEBAB_CASE)
public interface MessageUtilConfigurations {
    Optional<Boolean> enableDataswapDetection();

    Map<String, Map<String, MessageUtilConfiguration>> messageUtilConfigsMap();

    interface MessageUtilConfiguration {
        Optional<Boolean> enableDataswapDetection();
    }

}
```

And an YAML like: 
```yaml
message-util-configurations:
  enable-dataswap-detection: true
  message-util-configs-map:
    filter:
      default:
        enable-dataswap-detection: false
      get-jokes-uni:
        enable-dataswap-detection: true
    client:
      reaction-api:
        enable-dataswap-detection: true
      setup-api:
        enable-dataswap-detection: true
```

The following test fails: 

```java
    @Test
    void testNestingConfig() throws Exception {
        SmallRyeConfig config = new SmallRyeConfigBuilder()
                .withSources(new YamlConfigSource(
                        getClass().getClassLoader().getResource("example-nesting.yml")))
                .withMapping(MessageUtilConfigurations.class)
                .build();
        MessageUtilConfigurations root = config.getConfigMapping(MessageUtilConfigurations.class);
        assertEquals(2, root.messageUtilConfigsMap().keySet().size());
    }
```

**PS**: The bug was introduced by [this commit](https://github.com/smallrye/smallrye-config/commit/c0df101251e0d701e49b7c50ca428f8d17aa5c8f)

Here is the full Test case for reference purposes: 

```java
package io.smallrye.config.source.yaml;

import io.smallrye.config.ConfigMapping;
import io.smallrye.config.SmallRyeConfig;
import io.smallrye.config.SmallRyeConfigBuilder;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class YamlConfigNestingTest {

    @Test
    void testNestingConfig() throws Exception {
        SmallRyeConfig config = new SmallRyeConfigBuilder()
                .withSources(new YamlConfigSource(
                        getClass().getClassLoader().getResource("example-nesting.yml")))
                .withMapping(MessageUtilConfigurations.class)
                .build();
        MessageUtilConfigurations root = config.getConfigMapping(MessageUtilConfigurations.class);
         
        assertEquals(2, root.messageUtilConfigsMap().keySet().size(), "Should have returned 'filter' and 'client'");
    }

    @ConfigMapping(prefix = "message-util-configurations", namingStrategy = ConfigMapping.NamingStrategy.KEBAB_CASE)
    public interface MessageUtilConfigurations {
        Optional<Boolean> enableDataswapDetection();

        Map<String, Map<String, MessageUtilConfiguration>> messageUtilConfigsMap();

        interface MessageUtilConfiguration {
            Optional<Boolean> enableDataswapDetection();
        }

    }
}
```
