### ISSUE TITLE
Override config properties

### ISSUE THREAD

**Issue by Dosexe** [smallrye/smallrye-config#820]
What is the preferred way of overriding config properties from libraries? 
I have an app which uses 
```yml
mp:
  messaging:
    incoming:
      my_queue:
        connector: smallrye-rabbitmq
        queue:
          name: my_queue
```
And a library which corresponds to the same queue
```yml
mp:
  messaging:
    outgoing:
      my_queue:
        connector: smallrye-rabbitmq
```

So what is the preferred way of ignoring second config in the app? I tried `RelocateConfigSourceInterceptor` and `ConfigSourceInterceptor` they are called, but seems it doesn't help to ignore or override second config.
