### ISSUE TITLE
Support for properties with dynamic names (e.g. Quarkus' "%dev,test") in Map-based configuration

### ISSUE THREAD

**Issue by jskillin-idt** [smallrye/smallrye-config#986]
I was told to report an issue here as the issue stems from a lack of feature support in smallrye-config:

Given this Quarkus application.yaml file:
```yaml
"%dev,test":
  quarkus:
    keycloak:
      devservices:
        roles:
          alice: sample_role
```
...I was expecting Quarkus (and underneath, it sounds like smallrye-config) to understand that the "quarkus" dictionary to belong to both the "dev" and "test" Quarkus profiles, but Quarkus failed to apply this configuration.

Instead, I was forced to break out the config into two duplicate copies:
```yaml
---
"%dev":
  quarkus:
    keycloak:
      devservices:
        roles:
          alice: sample_role
---
"%test":
  quarkus:
    keycloak:
      devservices:
        roles:
          alice: sample_role
```

~~This works as expected if I used a `properties` formatted file instead, so this is specific to how YAML is interpreted.~~ Update: this is not true. This does not work whenever the configuration terminates in a Map.
